services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hamza2018
      POSTGRES_DB: quizminds
    ports:
      - 5000:5000
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - cnx
  app:
    ports:
      - 8080:8080
    image: 'quizminds-app:latest'
    build:
      context: .
    container_name: quizmindsApp
    networks:
      - cnx
volumes:
  db:
    driver: local
networks:
  cnx: